repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-added-large-files
  - repo: https://github.com/omnilib/ufmt
    rev: v1.3.1
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 21.12b0
          - usort == 1.0.0
#  - repo: https://github.com/psf/black
#    rev: 21.12b0
#    hooks:
#      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
