name: Build Project

on: [push]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0 # Increase this value to reset cache if environment.yml has not changed
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      - name: Cache pip dependencies
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0 # Increase this value to reset cache if requirement files did not change
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.CACHE_NUMBER }}-${{ hashFiles('poetry.lock') }}
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: true
          environment-file: environment.yml
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Install pip dependencies
        shell: bash -l {0}
        run: |
          poetry env info
          poetry install
          pip list
      - name: Run tests using pytest
        shell: bash -l {0}
        run: |
          invoke test --cov
